fix: don't exclude full */var/* folder in Pimcore PHPCS configuration
Error: PHPCS didn't scan anything when using in DDEV container
Discovered in version: 3.0.0-rc1
Caused by: exclude on */var/* which matches the /var/www/html root
Resolved with: removing this generic exclude, relying on the more specific excludes that are configured in /templates/files/pimcore/phpcs.xml