fix: file installer should prioritize project specific files
Discovered in: version 3.0.0-rc1
Error: within a Pimcore project, the `templates/files/default/grumphp.yml` instead of `templates/files/pimcore/grumphp.yml`
Caused by: the default file mapping was executed first, installing the `grumphp.yml` and the project-specific file mapping was executed second, ignoring the (by then) already existing `grumphp.yml`
Resolved with: installing the project specific files first