fix: perform most operations in post-install-cmd
Error: Composer didn't correctly recognize newly installed packages
Caused by: PackagesInstaller running in "post-package-install"
Resolved with: Running (most) installers in "post-install-cmd" instead

Resolves #60