fix: don't rewrite composer.json empty objects to arrays
Error: the installers writing changes to composer.json converted empty
objects to empty arrays
Caused by: using json_decode with associative true
Resolved with: use json_decode with associative false so that types
remain the same