fix: let PHPStan scan full project
Error: PHPStan exited with "[ERROR] No files found to analyse." during the commit hook when only committing files in the excluded section
Caused by: PHPStan really wants to scan the whole project, which makes sense because a change in one file can break another file (which was not part of your commit)
Resolved with: Setting `use_grumphp_paths` option to false, include `paths` in `phpstan.neon`

Resolves #51